/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.libraryadmin;

import business.WorkQueue.WorkRequest;
import business.account.AccountItem;
import business.book.Book;
import business.library.Library;
import business.runnable.PurchaseNewBookRunnable;
import business.system.LibSystem;
import java.awt.CardLayout;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jackey
 */
public class LibraryAdminJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Library library;
    private LibSystem system;
    /**
     * Creates new form LibraryAdminJPanel
     */
    public LibraryAdminJPanel() {
        initComponents();
    }

    public LibraryAdminJPanel(JPanel userProcessContainer, Library library, LibSystem system) {
        this.userProcessContainer = userProcessContainer;
        this.library = library;
        this.system = system;
        initComponents();
        populateTable();
        libnameText.setText(library.getName());
    }
    
    public void populateTable(){
        DefaultTableModel model = (DefaultTableModel) purchaseTable.getModel();       
        model.setRowCount(0);
        for(WorkRequest wr : library.getWorkQueue().getWorkRequestList()){
            Object[] row = new Object[7];
            row[0] = wr.getBook();
            row[1] = wr.getBook().getAuthor();
            row[2] = wr.getBook().getPress();
            row[3] = wr.getBook().getDate();
            row[4] = wr.getBook().getInprice();
            row[5] = wr.getRequestDate();
            row[6] = wr;
            model.addRow(row);
        }
    }
    
    public void addPurchaseToAccount(Book book, int num){
        AccountItem ai = library.getLibraryAccount().createAccountItem(AccountItem.Type.Spent);
        double total = book.getInprice() * num;
        ai.setMoney(total);
        ai.setDate(new Date());
        ai.setExplain(book.getName());
        ai.setReceiver(String.valueOf(num));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        libnameText = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        purchaseTable = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        amountSpinner = new javax.swing.JSpinner();
        purchaseBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        viewAdminBtn = new javax.swing.JButton();
        viewInvBtn = new javax.swing.JButton();
        viewAccountBtn = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setText("Library Admin Work Area");

        jLabel2.setText("Library Name:");

        libnameText.setEnabled(false);

        purchaseTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Book Name", "Author", "Press", "Publish Date", "Purchase Price", "Request Date", "Request Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        purchaseTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(purchaseTable);

        jLabel4.setText("New Book Purchase Apply:");

        purchaseBtn.setText("Purchase");
        purchaseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purchaseBtnActionPerformed(evt);
            }
        });

        jLabel5.setText("Amount:");

        viewAdminBtn.setText("View Book Admin");
        viewAdminBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewAdminBtnActionPerformed(evt);
            }
        });

        viewInvBtn.setText("View Book Inventory");
        viewInvBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewInvBtnActionPerformed(evt);
            }
        });

        viewAccountBtn.setText("View Library Account");
        viewAccountBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewAccountBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(viewInvBtn)
                        .addGap(18, 18, 18)
                        .addComponent(viewAccountBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(amountSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(purchaseBtn))
                    .addComponent(jLabel4)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(libnameText, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(viewAdminBtn))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 784, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
            .addGroup(layout.createSequentialGroup()
                .addGap(279, 279, 279)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(libnameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewAdminBtn))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amountSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(purchaseBtn)
                    .addComponent(jLabel5)
                    .addComponent(viewInvBtn)
                    .addComponent(viewAccountBtn))
                .addContainerGap(102, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void viewAdminBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAdminBtnActionPerformed
        // TODO add your handling code here:
        ViewBookAdminJPanel vbajp = new ViewBookAdminJPanel(userProcessContainer, library, system);
        userProcessContainer.add("ViewBookAdminJPanel", vbajp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_viewAdminBtnActionPerformed

    private void viewInvBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewInvBtnActionPerformed
        // TODO add your handling code here:
        ViewInventoryJPanel vijp = new ViewInventoryJPanel(userProcessContainer, library);
        userProcessContainer.add("ViewInventoryJPanel", vijp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_viewInvBtnActionPerformed

    private void viewAccountBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAccountBtnActionPerformed
        // TODO add your handling code here:
        ViewAccountJPanel vajp = new ViewAccountJPanel(userProcessContainer, library);
        userProcessContainer.add("ViewAccountJPanel", vajp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_viewAccountBtnActionPerformed

    private void purchaseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purchaseBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = purchaseTable.getSelectedRow();
        if(selectedRow >= 0){
            int buyNum = (Integer)amountSpinner.getValue();
            if(buyNum == 0){
                JOptionPane.showMessageDialog(null, "Please Purchase More Than Zero!");
                return;
            }
            else{
                Book book = (Book)purchaseTable.getValueAt(selectedRow, 0);
                book.setAmount(buyNum);
                book.setLocation("A00-000");
                library.getBookCatalog().getBookList().add(book);
                addPurchaseToAccount(book, buyNum);
                WorkRequest wr = (WorkRequest)purchaseTable.getValueAt(selectedRow, 6);
                wr.setStatus("Processed");
                populateTable();
                JOptionPane.showMessageDialog(null, "Success!");
                PurchaseNewBookRunnable pnbr = new PurchaseNewBookRunnable(library, book);
                Thread t1 = new Thread(pnbr);
                t1.start();
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "No Book Selected");
            return;
        }
    }//GEN-LAST:event_purchaseBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner amountSpinner;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField libnameText;
    private javax.swing.JButton purchaseBtn;
    private javax.swing.JTable purchaseTable;
    private javax.swing.JButton viewAccountBtn;
    private javax.swing.JButton viewAdminBtn;
    private javax.swing.JButton viewInvBtn;
    // End of variables declaration//GEN-END:variables
}
