/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.superadmin;

import business.library.Library;
import business.system.LibSystem;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jackey
 */
public class SuperAdminJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private LibSystem system;
    /**
     * Creates new form SuperAdminJPanel
     */
    public SuperAdminJPanel() {
        initComponents();
    }

    public SuperAdminJPanel(JPanel userProcessContainer, LibSystem system) {
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        initComponents();
        populateTable();
    }
    
    public void populateTable(){
        DefaultTableModel model = (DefaultTableModel) libraryTable.getModel();       
        model.setRowCount(0);
        for(Library lib : system.getLibraryList()){
            Object[] row = new Object[1];
            row[0] = lib;
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        libraryTable = new javax.swing.JTable();
        viewDetailBtn = new javax.swing.JButton();
        addLibraryBtn = new javax.swing.JButton();
        addAdminBtn = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setText("Super Admin Work Area");

        libraryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "LibraryName"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        libraryTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(libraryTable);

        viewDetailBtn.setText("View Detail");
        viewDetailBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewDetailBtnActionPerformed(evt);
            }
        });

        addLibraryBtn.setText("Add new Library");
        addLibraryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addLibraryBtnActionPerformed(evt);
            }
        });

        addAdminBtn.setText("Add Library Admin");
        addAdminBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAdminBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(134, 134, 134)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addLibraryBtn)
                            .addComponent(viewDetailBtn)
                            .addComponent(addAdminBtn)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(jLabel1)))
                .addContainerGap(170, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(viewDetailBtn)
                        .addGap(62, 62, 62)
                        .addComponent(addLibraryBtn)
                        .addGap(66, 66, 66)
                        .addComponent(addAdminBtn))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void viewDetailBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewDetailBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = libraryTable.getSelectedRow();
        if(selectedRow >= 0){
            Library library = (Library)libraryTable.getValueAt(selectedRow, 0);
            ViewLibDetailJPanel vldjp = new ViewLibDetailJPanel(userProcessContainer, system, library);
            userProcessContainer.add("ViewLibDetailJPanel", vldjp);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }
        else{
            JOptionPane.showMessageDialog(null, "No Library Selected");
            return;
        }
        
    }//GEN-LAST:event_viewDetailBtnActionPerformed

    private void addLibraryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addLibraryBtnActionPerformed
        // TODO add your handling code here:
        AddLibraryJPanel aljp = new AddLibraryJPanel(userProcessContainer, system);
        userProcessContainer.add("AddLibraryJPanel", aljp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_addLibraryBtnActionPerformed

    private void addAdminBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAdminBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = libraryTable.getSelectedRow();
        if(selectedRow >= 0){
            Library library = (Library)libraryTable.getValueAt(selectedRow, 0);
            AddLibraryAdminAccountJPanel alaajp = new AddLibraryAdminAccountJPanel(userProcessContainer, library);
            userProcessContainer.add("AddLibraryAdminAccountJPanel", alaajp);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }
        else{
            JOptionPane.showMessageDialog(null, "No Library Selected");
            return;
        }
    }//GEN-LAST:event_addAdminBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addAdminBtn;
    private javax.swing.JButton addLibraryBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable libraryTable;
    private javax.swing.JButton viewDetailBtn;
    // End of variables declaration//GEN-END:variables
}
